### ISSUE TITLE
Unable to test the action locally in workflow

### ISSUE THREAD

**Issue by dgilbert-foreflight** [actions/typescript-action#1005]
The workflow which runs a test of the local action doesn't appear to work anymore.

```
- name: Test Local Action
        id: test-action
        uses: ./
        with:
          milliseconds: 2000
```

https://github.com/actions/typescript-action/actions/runs/12981582939/job/36200199094
