### ISSUE TITLE
Editing PR first comment or title does not trigger a workflow

### ISSUE THREAD

**Issue by eine** [actions/typescript-action#27]
I'm trying to write an action based on this template that will check/watch the first comment of PRs. Each time the comment is edited/updated, the workflow should be executed. I tried with the following workflow:

```
name: 'Self-labelling'
on: [pull_request, issues, issue_comment]
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: 1138-4EB/actions@tip
```

I found that it is executed when I open a PR, respond to a PR (new comment), open an issue, respond to an issue, edit the body of the first comment of an issue, etc. However, it does not work neither when editing the first comment of a PR nor when editing the title of a PR. Therefore, it seems that the only option to trigger the workflow after the PR is created is to synchronize it again. I would expect that any of these actions would trigger `pull_request edited`, `issue_comment edited` or `issues edited`.

/cc @damccorm

**Comment by ibrasho** [comment]
This is expected. By default, the `pull_request` event only triggers on these actions: `opened`, synchronize` and `reopened`. [1](https://help.github.com/en/articles/events-that-trigger-workflows#example-triggering-workflows-when-a-pull_request-is-assigned).

You need to do the following:
```yaml
on:
  pull_request:
    types: edited
  issues:
  issue_comment:
```

**Comment by bryanmacfarlane** [comment]
Thanks @ibrasho

**Comment by AllanOricil** [comment]
I need to reopen this. I just edited my title and it is no longer triggering my action.


````yml
name: Bump Version Workflow

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    branches:
      - main

  workflow_dispatch:

jobs:
  get-mulesoft-apps:
    name: Get Mulesoft Apps
    uses: VodafoneIS/mulesoft/.github/workflows/get-mulesoft-apps.yml@main

  bump-version:
    name: bump version
    needs: get-mulesoft-apps
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vodafoneis/mulesoft-build-image:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        MULESOFT_APP: ${{ fromJson(needs.get-mulesoft-apps.outputs.MULESOFT_APPS) }}

    defaults:
      run:
        working-directory: ${{ matrix.MULESOFT_APP }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: print app name
        run: echo ${{ matrix.MULESOFT_APP }}

      - uses: fregante/setup-git-user@v1

      - name: set bump type
        id: get-bump-type
        run: |
          bump_type=$(/scripts/get_bump_type.sh -a ${{ matrix.MULESOFT_APP }} -t ${{ github.event.pull_request.title }} -b ${{ github.event.pull_request.body}})
          echo "::set-output name=BUMP_TYPE::$bump_type"

      - name: bump version
        run: /scripts/bump_version.sh -a ${{ matrix.MULESOFT_APP }} -b ${{ steps.get-bump-type.outputs.BUMP_TYPE }}


````

**Comment by obryckim** [comment]
@AllanOricil - Did you ever resolve this? I am seeing the same behavior where the `edited` event is not triggering the workflow, even with

```yaml
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
```
