### ISSUE TITLE
Warning: `pre` execution is not supported for local action from './'

### ISSUE THREAD

**Issue by zijchen** [actions/typescript-action#564]
I am one of the contributors for [Azure/sql-action](https://github.com/Azure/sql-action), and we have a workflow defined [here](https://github.com/Azure/sql-action/blob/master/.github/workflows/pr-check.yml) that uses `./` to run our action and test some functionalities. I followed [this guide](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspre) to add a `pre` script for some setup code, like this:
```yml
runs:
  using: 'node12'
  pre: 'lib/setup.js'
  main: 'lib/main.js'
```

But in our workflow, it seems like that is ignored
> Warning: `pre` execution is not supported for local action from './'

Is there a way to execute the `pre` script even for using `./`?

A workaround would be to move the `pre` script into our main function, but we'd like to keep the setup code separate if possible.

**Comment by LecrisUT** [comment]
I don't think that is equivalent, e.g. how can we make the github actions testable, especially for forks.

**Comment by nwalters512** [comment]
This workaround makes it impossible to test changes to an action in the repo in which it's developed, which I imagine is a very common use case for folks who are writing and referencing local actions. It'd work if one could write `- uses: <owner>/<repo>/my-action@${{ github.sha }}`, but that's not allowable.

Can someone from GitHub explain _why_ `pre:` and friends aren't supported for local actions?

**Comment by ncalteen** [comment]
I did some checking internally to see why `pre` is not supported for local actions. The reason is because the action itself is downloaded and run _after_ the job starts and any `pre` steps have run. On the other hand, `post` does work when referencing local actions.

As far as testing the action, you should be able to reference either your fork repo or branch name without issue:

```yaml
- uses: <owner>/<fork-repo>@main
- uses: <owner>/<action-repo>@<feature-branch>
```

**Comment by ncalteen** [comment]
Closing due to lack of activity. If you'd like to revisit this please open a new issue and provide any additional details that may be useful :)

**Comment by LecrisUT** [comment]
There is no activity because the request is clear. We need it for relative path. That's the form that works for gh actions to allow PRs, otherwise whenever a new PR is made, they need to point the unit tests to their fork, run the tests and point them back to the original repo before merging

**Comment by ncalteen** [comment]
Apologies! I misunderstood the request :/

I was able to find more info [here](https://github.com/actions/runner/blob/main/docs/adrs/0361-wrapper-action.md). In particular:

_Action referenced from local repository (`./my-action`) won't get `pre` setup correctly since the repository haven't checked-out during job initialization. We can't use GitHub api to download the repository since there is about a 3 minute delay between git push and the new commit available to download using GitHub api._

As far as current workarounds, yes you can fork the action repo, update the workflow to reference the forked repo name, and then update to the original repo name before submitting the PR.

Another option would be to convert to a composite action and move the `pre`/`post` steps into the "actual" workflow steps. E.g. instead of this:

```yml
runs:
  using: 'node12'
  pre: 'lib/setup.js'
  main: 'lib/main.js'
```

1. Convert the `pre` step to it's own action

   ```yml
   name: Setup Pre Action
   description: Setup Pre Action

   runs:
     using: node20
     main: ../lib/pre.js
   ```

2. Convert the `main` step to a separate action

   ```yml
   name: Main Action
   description: Main Action

   runs:
     using: node20
     main: ../lib/index.js
   ```

3. Call both actions in a composite

   ```yml
   name: Composite Action
   description: A composite action for demo purposes

   runs:
     using: composite
     steps:
       # This was previously a `pre` step in a Node.js action
       - name: Setup
         uses: ./setup-action

       # This was previously a `main` step in a Node.js action
       - name: Main
         uses: ./main-action
   ```

I created a trivial reproduction [here](https://github.com/ncalteen/composite-pre-example) if that helps. The benefit there is you shouldn't need to rename anything when forking and making updates.
