### ISSUE TITLE
Pre & Post action config recommendation?

### ISSUE THREAD

**Issue by sayhiben** [actions/typescript-action#811]
Firstly, I want to say thank you to @ncalteen for showing ownership over this repository - it's very likely more important than you're being given credit for, and I **deeply** appreciate the support and leadership you've displayed here over the past months

What I could use help with is the package.json setup for pre and post actions. It looks like I've made a mistake that's causing my index.ts file to replace all three files at dist/index.js, dist/pre.js, and dist/post.js

Is there a recommended package.json or other configuration that can I can use (and possibly be added to the readme) to ensure my build produces all three entrypoints?

Here's the relevant portion of my package.json scripts that I hoped to produce three entrypoints, one each from src/pre.ts, src/post.ts, and src/index.ts, but it seems to always execute the main script in src/index.ts in the action's "post" lifecycle, and I'm not sure what to do about it:

```yaml
  "scripts": {
    "bundle": "npm run format:write && npm run package",
    "ci-test": "jest",
    "format:write": "prettier --write '**/*.ts'",
    "format:check": "prettier --check '**/*.ts'",
    "lint": "npx eslint . -c ./.github/linters/.eslintrc.yml",
    "package:index": "ncc build src/index.ts -o dist/index && mv dist/index/index.js dist/ && rm -rf dist/index",
    "package:pre": "ncc build src/pre.ts -o dist/pre && mv dist/pre/index.js dist/pre/pre.js && mv dist/pre/pre.js dist/ && rm -rf dist/pre",
    "package:post": "ncc build src/index.ts -o dist/post && mv dist/post/index.js dist/post/post.js && mv dist/post/post.js dist/post.js && rm -rf dist/post",
    "package": "npm run package:index && npm run package:pre && npm run package:post",
    "package:watch": "npm run package -- --watch",
    "test": "(jest -i && make-coverage-badge --output-path ./badges/coverage.svg) || make-coverage-badge --output-path ./badges/coverage.svg",
    "all": "npm run format:write && npm run lint && npm run test && npm run package"
  },
```

Thanks in advance. I'll post an update if I figure it out on my own ahead of time
